Document: ktap
Title: Debian ktap Manual
Author: <insert document author here>
Abstract: This manual describes what ktap is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/ktap/ktap.sgml.gz

Format: postscript
Files: /usr/share/doc/ktap/ktap.ps.gz

Format: text
Files: /usr/share/doc/ktap/ktap.text.gz

Format: HTML
Index: /usr/share/doc/ktap/html/index.html
Files: /usr/share/doc/ktap/html/*.html
